FROM quay.io/dtrifiro/vllm:fast-ibm-add07008 as vllm-grpc-adapter

USER root

# Create a temporary directory
RUN mkdir /tmp/vllm-repo

# Clone the ibm-20240930 branch from the repository into the temporary directory
RUN git clone -b ibm-20240930 https://github.com/opendatahub-io/vllm.git /tmp/vllm-repo

# Ensure the destination directory exists
RUN mkdir -p /opt/vllm/lib64/python3.11/site-packages/vllm

# Copy the updated vllm source code from the temporary directory to the installed location to overwrite the installed Python code
COPY --from=vllm-grpc-adapter /tmp/vllm-repo /opt/vllm/lib64/python3.11/site-packages/vllm/

# Clean up by removing the temporary directory
RUN rm -rf /tmp/vllm-repo

# Install the vllm-tgis-adapter
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install git+https://github.com/opendatahub-io/vllm-tgis-adapter@version-bugfix  

ENV GRPC_PORT=8033 \
    PORT=8000 \
    DISABLE_LOGPROBS_DURING_SPEC_DECODING=false

USER 2000
ENTRYPOINT ["python3", "-m", "vllm_tgis_adapter", "--uvicorn-log-level=warning"]
