# Using the intermediate image cuda-pr-<pr-number>
FROM quay.io/opendatahub/vllm:cuda-pr-221 as vllm-grpc-adapter

USER root

# Copy source code changes into the installed location to overwrite the installed python code
COPY vllm /opt/vllm/lib64/python3.12/site-packages/vllm

RUN --mount=type=cache,target=/root/.cache/pip \
    --mount=type=cache,target=/root/.cache/uv \
    uv pip install "git+https://github.com/opendatahub-io/vllm-tgis-adapter@ibm-20241106-adapter"

ENV GRPC_PORT=8033 \
    PORT=8000 \
    # As an optimization, vLLM disables logprobs when using spec decoding by
    # default, but this would be unexpected to users of a hosted model that
    # happens to have spec decoding
    # see: https://github.com/vllm-project/vllm/pull/6485
    DISABLE_LOGPROBS_DURING_SPEC_DECODING=false

USER 2000
ENTRYPOINT ["python3", "-m", "vllm_tgis_adapter", "--uvicorn-log-level=warning"]
