FROM quay.io/dtrifiro/vllm:fast-ibm-add07008 as vllm-grpc-adapter

USER root

# Clean the destination directory before cloning
RUN rm -rf /opt/vllm/lib64/python3.12/site-packages/vllm/*

# Clone the ibm-20240930 branch from the repository directly into the destination directory
RUN git clone -b ibm-20240930 https://github.com/opendatahub-io/vllm.git /opt/vllm/lib64/python3.12/site-packages/vllm/

# Clean up by removing the temporary directory
RUN rm -rf /tmp/vllm-repo

# Install the vllm-tgis-adapter
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install git+https://github.com/opendatahub-io/vllm-tgis-adapter@version-bugfix  

ENV GRPC_PORT=8033 \
    PORT=8000 \
    DISABLE_LOGPROBS_DURING_SPEC_DECODING=false

USER 2000
ENTRYPOINT ["python3", "-m", "vllm_tgis_adapter", "--uvicorn-log-level=warning"]
